config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'
  get 'users' => 'users#index'

  resources :teachers

  resources :lesson_has_teachers

  resources :locations

  resources :pupil_has_years

  resources :years

  resources :payments

  resources :pupil_has_lessons

  resources :pupils

  resources :lessons

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/pupil_has_year.rb
class PupilHasYear < ActiveRecord::Base
  belongs_to :year
  belongs_to :payment
  belongs_to :pupil

  validate :no_dupe_registrations#, only: [:create]

private
  def no_dupe_registrations
    phs = PupilHasYear.where(pupil_id: self.pupil_id, year_id: self.year_id).first
    if phs != nil && (self.new_record? || phs.id != self.id)
      errors.add(:pupil_id, " is already registered for this year!")
    end
  end
end

app/controllers/pupil_has_years_controller.rb
class PupilHasYearsController < ApplicationController
  before_action :set_pupil_has_year, only: [:show, :edit, :update, :destroy]

  # GET /pupil_has_years
  # GET /pupil_has_years.json
  def index
    @years = Year.all.to_a
    @payments = PupilHasYear.find_by_sql("SELECT pupil_id, year_id, amount, adjusted_price
     FROM pupil_has_years AS phy
      INNER JOIN pupils AS pu
      ON pu.id = phy.pupil_id
      LEFT OUTER JOIN payments AS p
       ON phy.payment_id = p.id
     WHERE pu.user_id=#{current_user.id};").to_a

    # Convenience method to rapidly scan through and find a particular pupil_year
    @payments.define_singleton_method(:find_by_pupil_year) do |*args|
      puts args.inspect
      self.each do |p|
        if p.pupil_id == args[0] && p.year_id == args[1]
          puts "YAY! #{p.inspect}"
          return p
        end
      end
      return nil
    end

   @pupil_has_years = PupilHasYear.all #.sort_by(:year, :pupil_id)
  end

  # GET /pupil_has_years/1
  # GET /pupil_has_years/1.json
  def show
  end

  # GET /pupil_has_years/new
  def new
    year = Year.last
    @pupil_has_year = year.pupil_has_years.new(adjusted_price: year.price)
  end

  # GET /pupil_has_years/1/edit
  def edit
  end

  # POST /pupil_has_years
  # POST /pupil_has_years.json
  def create
    @pupil_has_year = PupilHasYear.new(pupil_has_year_params)

    respond_to do |format|
      if @pupil_has_year.save
        format.html { redirect_to pupil_has_years_path, notice: 'Pupil has year was successfully created.' }
        format.json { render :show, status: :created, location: @pupil_has_year }
      else
        format.html { render :new }
        format.json { render json: @pupil_has_year.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pupil_has_years/1
  # PATCH/PUT /pupil_has_years/1.json
  def update
    respond_to do |format|
      if @pupil_has_year.update(pupil_has_year_params)
        format.html { redirect_to pupil_has_years_path, notice: 'Pupil has year was successfully updated.' }
        format.json { render :show, status: :ok, location: @pupil_has_year }
      else
        format.html { render :edit }
        format.json { render json: @pupil_has_year.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pupil_has_years/1
  # DELETE /pupil_has_years/1.json
  def destroy
    @pupil_has_year.destroy
    respond_to do |format|
      format.html { redirect_to pupil_has_years_url, notice: 'Pupil has year was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pupil_has_year
      @pupil_has_year = PupilHasYear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pupil_has_year_params
      params.require(:pupil_has_year).permit(:year_id, :payment_id, :pupil_id, :adjusted_price)
    end
end

app/helpers/pupil_has_years_helper.rb
module PupilHasYearsHelper
end

app/views/pupil_has_years/_form.html.erb
  <% if @pupil_has_year.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@pupil_has_year.errors.count, "error") %> prohibited this registration from being saved:</p>

      <ul>
      <% @pupil_has_year.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for @pupil_has_year, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :adjusted_price, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :adjusted_price, :class => 'text-field form-control' %>
    </div>
    <div class="col-md-10">
      <%= f.collection_select :year_id, Year.all, :id, :year %>
    </div>
    <div class="col-md-10">
      <%= f.collection_select :pupil_id, Pupil.all, :id, :full_name %>
    </div>

  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  pupil_has_years_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/pupil_has_years/edit.html.erb
<%- model_class = PupilHasYear -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => PupilHasYear %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pupil_has_years/index.html.erb
<%- model_class = PupilHasYear -%>
<div class="page-header">
  <h1>Registrations</h1>
</div>
<table>
  <tr>
    <th></th>
    <% @years.each do |y| %>
      <th><%= y.year %></th>
    <% end %>
  </tr>
  <% Pupil.all.each do |p| %>
  <tr>
    <td><%= p.full_name %></td>
    <% @years.each do |y| %>
      <% pmt = @payments.find_by_pupil_year(p.id, y.id) %>
      <td style="background-color: <%=
       pmt ? (pmt.amount ? "green" : "red") : "black" %>"><%= pmt ? link_to(pmt.amount.inspect, pmt.amount ? edit_payment_path(pmt) : new_payment_path(pupil_id: p.id, year_id: y.id)) : "X" %></td>
    <% end %>
  </tr>
  <% end %>
</table>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Year</th>
      <th>Pupil</th>
      <th> Normal Price</th>
      <th><%= model_class.human_attribute_name(:adjusted_price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pupil_has_years.each do |pupil_has_year| %>
      <tr>
        <td><%= pupil_has_year.id %></td>
        <td><%= pupil_has_year.year.year %></td>
        <td><%= link_to pupil_has_year.pupil.full_name, edit_pupil_path(pupil_has_year.pupil) %></td>
        <td><%= pupil_has_year.year.price %></td>
        <td><%= pupil_has_year.adjusted_price %></td>
        <td><%=l pupil_has_year.created_at, format: :long %></td>
        <td>
          <%= link_to edit_pupil_has_year_path(pupil_has_year), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to pupil_has_year_path(pupil_has_year), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_pupil_has_year_path,
            :class => 'btn btn-primary' %>

app/views/pupil_has_years/new.html.erb
<%- model_class = PupilHasYear -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => PupilHasYear %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pupil_has_years/show.html.erb
<%- model_class = PupilHasYear -%>
<div class="page-header">
  <h1><%=t '.title', :default => PupilHasYear %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:adjusted_price) %></dt>
      <dd><pre class="prettyprint"><%= @pupil_has_year.adjusted_price %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              pupil_has_years_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_pupil_has_year_path(@pupil_has_year), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              pupil_has_year_path(@pupil_has_year),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>