config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'
  get 'users' => 'users#index'

  resources :teachers

  resources :lesson_has_teachers

  resources :locations

  resources :pupil_has_years

  resources :years

  resources :payments

  resources :pupil_has_lessons

  resources :pupils

  resources :lessons

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/pupil_has_lesson.rb
class PupilHasLesson < ActiveRecord::Base
  belongs_to :pupil
  belongs_to :lesson
  belongs_to :payment


  validate :no_dupe_lessons#, only: [:create]

private
  def no_dupe_lessons
    phl = PupilHasLesson.where(pupil_id: self.pupil_id, lesson_id: self.lesson_id).first
    if phl != nil && (self.new_record? || phl.id != self.id)
      errors.add(:pupil_id, " is already registered for this lesson!")
    end
  end
end

app/controllers/pupil_has_lessons_controller.rb
class PupilHasLessonsController < ApplicationController
  before_action :set_pupil_has_lesson, only: [:show, :edit, :update, :destroy]

  # GET /pupil_has_lessons
  # GET /pupil_has_lessons.json
  def index
    @pupil_has_lessons = PupilHasLesson.all
    @lessons = Lesson.all.to_a
    @payments = PupilHasLesson.find_by_sql("SELECT * FROM pupil_has_lessons;").to_a


    @payments.define_singleton_method(:find_by_pupil_lesson) do |*args|
      puts args.inspect
      self.each do |l|
        if l.lesson_id == args[0] && l.lesson_id == args[1]
          puts "#{l.inspect}"
          return l
        end
      end
      return nil
    end
  end

  # GET /pupil_has_lessons/1
  # GET /pupil_has_lessons/1.json
  def show
  end

  # GET /pupil_has_lessons/new
  def new
    lesson = Lesson.last
    @pupil_has_lesson = PupilHasLesson.new(adjusted_price: lesson.price)
  end

  # GET /pupil_has_lessons/1/edit
  def edit
  end

  # POST /pupil_has_lessons
  # POST /pupil_has_lessons.json
  def create
    @pupil_has_lesson = PupilHasLesson.new(pupil_has_lesson_params)

    respond_to do |format|
      if @pupil_has_lesson.save
        format.html { redirect_to pupil_has_lessons_path, notice: 'Pupil has lesson was successfully created.' }
        format.json { render :show, status: :created, location: @pupil_has_lesson }
      else
        format.html { render :new }
        format.json { render json: @pupil_has_lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pupil_has_lessons/1
  # PATCH/PUT /pupil_has_lessons/1.json
  def update
    respond_to do |format|
      if @pupil_has_lesson.update(pupil_has_lesson_params)
        format.html { redirect_to pupil_has_lessons_path, notice: 'Pupil has lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @pupil_has_lesson }
      else
        format.html { render :edit }
        format.json { render json: @pupil_has_lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pupil_has_lessons/1
  # DELETE /pupil_has_lessons/1.json
  def destroy
    @pupil_has_lesson.destroy
    respond_to do |format|
      format.html { redirect_to pupil_has_lessons_url, notice: 'Pupil has lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pupil_has_lesson
      @pupil_has_lesson = PupilHasLesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pupil_has_lesson_params
      params.require(:pupil_has_lesson).permit(:pupil_id, :lesson_id, :payment_id, :adjusted_price)
    end
end

app/helpers/pupil_has_lessons_helper.rb
module PupilHasLessonsHelper
end

app/views/pupil_has_lessons/_form.html.erb
 <% if @pupil_has_lesson.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@pupil_has_lesson.errors.count, "error") %> prohibited this lesson sign up from being saved:</p>

      <ul>
      <% @pupil_has_lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for @pupil_has_lesson, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :adjusted_price, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :adjusted_price, :class => 'text-field form-control' %>
    </div>
    <div class="col-md-10">
      <%= f.collection_select :lesson_id, Lesson.all, :id, :title %>
    </div>
    <div class="col-md-10">
      <%= f.collection_select :pupil_id, Pupil.all, :id, :full_name %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  pupil_has_lessons_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/pupil_has_lessons/edit.html.erb
<%- model_class = PupilHasLesson -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => PupilHasLesson %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pupil_has_lessons/index.html.erb
<%- model_class = PupilHasLesson -%>
<div class="page-header">
  <h1>Lesson Enrollments</h1>
</div>
<table>
  <tr>
    <th></th>
    <% @lessons.each do |l| %>
      <th><%= l.genre %> <%=l.grade%></th>
    <% end %>
  </tr>
  <% Pupil.all.each do |p| %>
  <tr>
    <td><%= p.full_name %></td>
    <% @lessons.each do |l| %>
      <% pmt = @payments.find_by_pupil_lesson(p.id, l.id) %>
      <%#= raise l.id.inspect %>
      <td style="background-color: <%=
       pmt ? (pmt.adjusted_price ? "green" : "red") : "black" %>"><%= pmt ? link_to(pmt.adjusted_price.inspect, pmt.adjusted_price ? edit_payment_path(pmt) : new_payment_path(pupil_id: p.id, lesson_id: l.id)) : "X" %></td>
    <% end %>
  </tr>
  <% end %>
</table>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Pupil</th>
      <th>Class</th>
      <th>Normal Price</th>
      <th><%= model_class.human_attribute_name(:adjusted_price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pupil_has_lessons.each do |pupil_has_lesson| %>
      <tr>
        <td><%= pupil_has_lesson.id %></td>
        <td><%= link_to pupil_has_lesson.pupil.full_name, edit_pupil_path(pupil_has_lesson.pupil) %></td>
        <td><%= link_to pupil_has_lesson.lesson.genre, lessons_path(pupil_has_lesson.lesson.genre)%> Grade <%= pupil_has_lesson.lesson.grade%></td>
        <td><%= pupil_has_lesson.lesson.price %></td>
        <td><%= pupil_has_lesson.adjusted_price %></td>

        <td><%=l pupil_has_lesson.created_at, format: :long %></td>
        <td>
          <%= link_to edit_pupil_has_lesson_path(pupil_has_lesson), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to pupil_has_lesson_path(pupil_has_lesson), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_pupil_has_lesson_path,
            :class => 'btn btn-primary' %>

app/views/pupil_has_lessons/new.html.erb
<%- model_class = PupilHasLesson -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => PupilHasLesson %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pupil_has_lessons/show.html.erb
<%- model_class = PupilHasLesson -%>
<div class="page-header">
  <h1><%=t '.title', :default => PupilHasLesson %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:adjusted_price) %></dt>
      <dd><pre class="prettyprint"><%= @pupil_has_lesson.adjusted_price %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              pupil_has_lessons_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_pupil_has_lesson_path(@pupil_has_lesson), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              pupil_has_lesson_path(@pupil_has_lesson),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>