config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'
  get 'users' => 'users#index'

  resources :teachers

  resources :lesson_has_teachers

  resources :locations

  resources :pupil_has_years

  resources :years

  resources :payments

  resources :pupil_has_lessons

  resources :pupils

  resources :lessons

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  has_many :pupil_has_lessons
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @items = PupilHasLesson.find_by_sql("SELECT p.id AS pupil_id, pay.kind, pay.id, p.first_name, p.last_name,
      pay.name, pay.adjusted_price
     FROM pupils AS p INNER JOIN
       (SELECT phy.pupil_id, y.id, 'R' AS kind, 'Registration for ' || y.year AS name, adjusted_price FROM years AS y INNER JOIN pupil_has_years AS phy ON y.id = phy.year_id WHERE payment_id IS NULL
        UNION ALL
        SELECT pupil_id, l.id, 'L' AS kind, l.genre || ' - ' || l.grade AS name, adjusted_price FROM lessons AS l INNER JOIN pupil_has_lessons AS phl ON l.id = phl.lesson_id WHERE payment_id IS NULL
        ) AS pay
      ON p.id = pay.pupil_id
     WHERE p.user_id = 1
     ORDER BY p.last_name, p.first_name;")

    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
    @payment.user = current_user

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:user_id)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for @payment, :html => { :class => 'form-horizontal form-model' } do |f| %>

  <div class="form-group">
    <div class="col-md-10">
      <%= f.collection_select :year_id, Year.all, :id, :year %>
    </div>
    <div class="col-md-10">
      <%= f.collection_select :pupil_id, Pupil.all, :id, :full_name %>
    </div>

    <%= f.text_field :amount %>
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  payments_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>


SELECT u.id AS user_id, u.first_name || ' ' || u.surname AS user_name,
  COUNT(*) AS pupil_count,
  SUM(COALESCE((SELECT SUM(adjusted_price) FROM pupil_has_years WHERE pupil_id = p.id AND payment_id IS NULL),0.0)) AS registration_total,
  SUM(COALESCE((SELECT SUM(adjusted_price) FROM pupil_has_lessons WHERE pupil_id = p.id AND payment_id IS NULL), 0.0)) AS lesson_total
  FROM users AS u
   INNER JOIN pupils AS p ON u.id = p.user_id
  GROUP BY u.id, u.first_name, u.surname
  ORDER BY u.surname, u.first_name;

app/views/payments/edit.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Payment %></h1>
</div>
<%= render :partial => 'form' %>

app/views/payments/index.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => Payment %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.id %></td>
        <td><%=l payment.created_at, format: :long %></td>
        <td>
          <%= link_to payment_path(payment), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to payment_path(payment), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_payment_path,
            :class => 'btn btn-primary' %>

app/views/payments/new.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Payment %></h1>
</div>
<%#= render :partial => 'form' %>

What the hell you're paying for:


<table class="table table-striped">
  <thead>
    <tr>
      <th>Pupil name</th>
      <th>What it is</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |i| %>
      <tr>
        <td><%= i.first_name%> <%= i.last_name%></td>
        <td><%= i.name%> </td>
        <td><%= i.adjusted_price%></td>
      </tr>
      
    <% end %>
  </tbody>
</table>

app/views/payments/show.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => Payment %></h1>
</div>

<div class="fieldset">
  <dl>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              payments_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_payment_path(@payment), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              payment_path(@payment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>